<?php
/** @var $block \Dholi\Widgets\Block\Widget\NewProduct */

if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
	$type = 'widget-new-grid';
	$mode = 'grid';

	$image = 'new_products_content_widget_grid';
	$items = $block->getProductCollection()->getItems();

	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
}
?>

<?php if ($exist) : ?>
	<div class="block widget widget-new-products <?php echo $mode ?>">
		<div class="block-title">
			<strong role="heading" aria-level="2"><?php echo $block->escapeHtml(__('New Products')) ?></strong>
		</div>
		<div class="block-content">
			<div class="products-<?php echo $mode ?> <?php echo $mode ?>">
				<ol class="product-items <?php echo $type ?>">
					<?php foreach ($items as $_item) : ?>
						<li class="product-item">
							<div class="product-item-info">
								<a href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>"
								   class="product-item-photo">
									<?php echo $block->getImage($_item, $image)->toHtml() ?>
								</a>
								<div class="product-item-details">
									<strong class="product-item-name">
										<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
										   href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>"
										   class="product-item-link">
											<?php echo $block->escapeHtml($_item->getName()) ?>
										</a>
									</strong>
									<?php echo $block->getProductPriceHtml($_item, $type); ?>
								</div>
							</div>
						</li>
					<?php endforeach ?>
				</ol>
			</div>
		</div>
	</div>
<?php endif; ?>
